-- 创建 NL2SQL 查询审计日志表，用于记录自然语言请求、计划、SQL、执行状态和结果摘要。
CREATE TABLE IF NOT EXISTS nl2sql_query_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  request_id VARCHAR(64) NOT NULL COMMENT '请求唯一标识',
  user_id VARCHAR(128) NOT NULL COMMENT '发起请求的用户标识',
  user_role VARCHAR(64) NOT NULL COMMENT '执行请求的角色',
  domain VARCHAR(128) NOT NULL COMMENT '命中的业务领域',
  datasource_id VARCHAR(128) NOT NULL COMMENT '最终访问的数据源 ID',
  natural_language_query TEXT NOT NULL COMMENT '原始自然语言问题',
  raw_plan_json JSON NULL COMMENT '模型输出的原始计划 JSON',
  resolved_plan_json JSON NULL COMMENT '后端解析后的规范化计划 JSON',
  built_sql MEDIUMTEXT NULL COMMENT 'Builder 生成的 SQL',
  validated_sql MEDIUMTEXT NULL COMMENT 'Guard 校验通过后的 SQL',
  query_mode VARCHAR(64) NOT NULL COMMENT '最终查询模式',
  result_kind VARCHAR(64) NOT NULL COMMENT '结果类型，如 aggregate 或 detail',
  detail_view_id VARCHAR(128) NULL COMMENT '明细查询命中的明细视图 ID',
  rejection_stage VARCHAR(64) NULL COMMENT '请求被拒绝时的阶段',
  execution_status VARCHAR(64) NOT NULL COMMENT '执行状态，如 success 或 failed',
  error_code VARCHAR(128) NULL COMMENT '稳定错误码',
  error_message_internal MEDIUMTEXT NULL COMMENT '内部错误详情，仅供排障',
  result_columns_json JSON NULL COMMENT '结果列预览 JSON',
  result_preview_json JSON NULL COMMENT '结果行预览 JSON',
  result_row_count INT NOT NULL DEFAULT 0 COMMENT '返回行数',
  latency_ms INT NOT NULL DEFAULT 0 COMMENT '端到端耗时毫秒数',
  llm_model VARCHAR(128) NULL COMMENT '规划阶段使用的模型',
  prompt_version VARCHAR(64) NULL COMMENT '提示词版本',
  sql_fingerprint VARCHAR(128) NULL COMMENT 'SQL 指纹',
  created_at DATETIME NOT NULL COMMENT '审计记录创建时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_nl2sql_query_log_request_id (request_id),
  KEY idx_nl2sql_query_log_domain_created_at (domain, created_at),
  KEY idx_nl2sql_query_log_status_created_at (execution_status, created_at)
) COMMENT='NL2SQL 查询审计日志表';
