datasource_id: ride_hailing_ro
database: ride_hailing
tables:
  - name: trip_orders
    comment: 订单事实表
    columns:
      - name: order_id
        data_type: varchar
        comment: 订单号
      - name: city_code
        data_type: varchar
        comment: 城市编码
      - name: service_type
        data_type: varchar
        comment: 服务类型
      - name: order_status
        data_type: varchar
        comment: 订单状态
      - name: called_at
        data_type: datetime
        comment: 呼叫时间
      - name: finished_at
        data_type: datetime
        comment: 完单时间
      - name: is_cancelled
        data_type: tinyint
        comment: 是否取消
      - name: driver_id
        data_type: varchar
        comment: 司机编号
  - name: drivers
    comment: 司机维表
    columns:
      - name: driver_id
        data_type: varchar
        comment: 司机编号
      - name: driver_name
        data_type: varchar
        comment: 司机姓名
